/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.42                       *
*        Compiled Aug  1 2017, 12:36:13                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 16_F.c                                                *
* Font:        Arial                                                 *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x46 (70)                                     *
* Character enabled:   0x50 (80)                                     *
* Character enabled:   0x53 (83)                                     *
* Character enabled:   0x3A (58)                                     *
* Character enabled:   0x20 (32)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font16_F;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0020[  6] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0030[ 20] = { /* code 0030, DIGIT ZERO */
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  __XXX___,
  _X___X__,
  X_XXX_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_XXX_X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0031[ 20] = { /* code 0031, DIGIT ONE */
  ________,
  ___X____,
  __XX____,
  _X_X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ___X____,
  __X_X___,
  _X__X___,
  X_X_X___,
  _XX_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X_X___,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0032[ 20] = { /* code 0032, DIGIT TWO */
  ________,
  __XXX___,
  _X___X__,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _XXXXX__,
  ________,
  __XXX___,
  _X___X__,
  X_XXX_X_,
  _X__X_X_,
  ____X_X_,
  ___X_X__,
  __X_X___,
  _X_XXX__,
  X_____X_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0033[ 20] = { /* code 0033, DIGIT THREE */
  ________,
  __XXX___,
  _X___X__,
  _____X__,
  ___XX___,
  _____X__,
  _____X__,
  _X___X__,
  __XXX___,
  ________,
  __XXX___,
  _X___X__,
  X_XXX_X_,
  _X_XX_X_,
  __X__X__,
  ___XX_X_,
  _X__X_X_,
  X_XXX_X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0034[ 20] = { /* code 0034, DIGIT FOUR */
  ________,
  ____X___,
  ___XX___,
  __X_X___,
  __X_X___,
  _X__X___,
  _XXXXX__,
  ____X___,
  ____X___,
  ________,
  ____X___,
  ___X_X__,
  __X__X__,
  _X_X_X__,
  _X_X_X__,
  X_XX_X__,
  X_____X_,
  _XXX_X__,
  ___X_X__,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0035[ 20] = { /* code 0035, DIGIT FIVE */
  ________,
  __XXXX__,
  __X_____,
  _X______,
  _XXXX___,
  _____X__,
  _____X__,
  _X___X__,
  __XXX___,
  ________,
  __XXXX__,
  _X____X_,
  _X_XXX__,
  X_XXX___,
  X____X__,
  _XXXX_X_,
  _X__X_X_,
  X_XXX_X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0036[ 20] = { /* code 0036, DIGIT SIX */
  ________,
  __XXX___,
  _X___X__,
  _X______,
  _XXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  __XXX___,
  _X___X__,
  X_XXX_X_,
  X_XXXX__,
  X____X__,
  X_XXX_X_,
  X_X_X_X_,
  X_XXX_X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0037[ 20] = { /* code 0037, DIGIT SEVEN */
  ________,
  _XXXXX__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  _XXXXX__,
  X_____X_,
  _XXX_X__,
  ___X_X__,
  __X_X___,
  __X_X___,
  _X_X____,
  _X_X____,
  _X_X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0038[ 20] = { /* code 0038, DIGIT EIGHT */
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  __XXX___,
  _X___X__,
  X_XXX_X_,
  X_XXX_X_,
  _X___X__,
  X_XXX_X_,
  X_X_X_X_,
  X_XXX_X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0039[ 20] = { /* code 0039, DIGIT NINE */
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXXX__,
  _____X__,
  _X___X__,
  __XXX___,
  ________,
  __XXX___,
  _X___X__,
  X_XXX_X_,
  X_X_X_X_,
  X_XXX_X_,
  _X____X_,
  _XXXX_X_,
  X_XXX_X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_003A[ 16] = { /* code 003A, COLON */
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  _X______,
  X_X_____,
  _X______,
  ________,
  ________,
  _X______,
  X_X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0046[ 20] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  _XXXXX__,
  _X______,
  _X______,
  _XXXX___,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  _XXXXX__,
  X_____X_,
  X_XXXX__,
  X_XXX___,
  X____X__,
  X_XXX___,
  X_X_____,
  X_X_____,
  X_X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0050[ 20] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  _XXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X______,
  _X______,
  _X______,
  ________,
  _XXXX___,
  X____X__,
  X_XXX_X_,
  X_X_X_X_,
  X_XXX_X_,
  X____X__,
  X_XXX___,
  X_X_____,
  X_X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Font16_F_0053[ 20] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  __XXXX__,
  _X____X_,
  _X______,
  __XX____,
  ____XX__,
  ______X_,
  _X____X_,
  __XXXX__,
  ________,
  __XXXX__,
  _X____X_,
  X_XXXX_X,
  X_XX__X_,
  _X__XX__,
  __XX__X_,
  _X__XX_X,
  X_XXXX_X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Font16_F_CharInfo[15] = {
   {   3,   3,   0,  11,   5, acGUI_Font16_F_0020 } /* code 0020, SPACE */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  10,   0,   3,   8, acGUI_Font16_F_0031 } /* code 0031, DIGIT ONE */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0033 } /* code 0033, DIGIT THREE */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0035 } /* code 0035, DIGIT FIVE */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0036 } /* code 0036, DIGIT SIX */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0037 } /* code 0037, DIGIT SEVEN */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0038 } /* code 0038, DIGIT EIGHT */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0039 } /* code 0039, DIGIT NINE */
  ,{   3,   8,   0,   5,   5, acGUI_Font16_F_003A } /* code 003A, COLON */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   7,  10,   0,   3,   8, acGUI_Font16_F_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   8,  10,   0,   3,   9, acGUI_Font16_F_0053 } /* code 0053, LATIN CAPITAL LETTER S */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font16_F_Prop5 = {
   0x0053 /* first character */
  ,0x0053 /* last character  */
  ,&GUI_Font16_F_CharInfo[ 14] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font16_F_Prop4 = {
   0x0050 /* first character */
  ,0x0050 /* last character  */
  ,&GUI_Font16_F_CharInfo[ 13] /* address of first character */
  ,&GUI_Font16_F_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font16_F_Prop3 = {
   0x0046 /* first character */
  ,0x0046 /* last character  */
  ,&GUI_Font16_F_CharInfo[ 12] /* address of first character */
  ,&GUI_Font16_F_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font16_F_Prop2 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_Font16_F_CharInfo[  1] /* address of first character */
  ,&GUI_Font16_F_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Font16_F_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Font16_F_CharInfo[  0] /* address of first character */
  ,&GUI_Font16_F_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font16_F = {
   GUI_FONTTYPE_PROP_FRM /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font16_F_Prop1}
  ,11 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

